"""chat_steps.seq monotonic order + index swap (ADR-021, BUG-5)

Adds ``chat_steps.seq BIGINT GENERATED ALWAYS AS IDENTITY`` so step reconstruction order is
deterministic (insertion order), NOT ``created_at``. On the server-side tool-loop (ADR-011,
site.*) tool_use + tool_result are written in one transaction → equal transaction-time
``created_at``; the random UUID-id tie-break could place tool_result before its tool_use →
orphan tool_result → Anthropic 400 → backend 502 (BUG-5). ``seq`` guarantees tool_use < tool_result
by insertion order. Replaces index ``ix_steps_session_created (session_id, created_at)`` with
``ix_steps_session_seq (session_id, seq)``; ``ix_steps_message_step`` is untouched.

Backfill keeps the prior historical order: existing rows get ``seq`` via
``ROW_NUMBER() OVER (ORDER BY created_at, id)`` (the previous order, incl. id tie-break), then the
identity sequence is advanced above max(seq) so new inserts never collide with backfilled values.

All steps run inside the single migration transaction (Alembic wraps upgrade()/downgrade() per
migration), so the column add + backfill + sequence restart + NOT NULL + index swap are atomic.

Chain: 0001 -> 0002 -> 0003 -> 0004 -> 0005 -> 0006 (single head). down_revision is the FULL
revision id of 0005 (``0005_embedded_auth_issuer``), NOT the short ``0005``.

Revision ID: 0006_chat_steps_seq
Revises: 0005_embedded_auth_issuer
Create Date: 2026-06-04
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0006_chat_steps_seq"
down_revision: str | None = "0005_embedded_auth_issuer"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # 1. Add the monotonic identity column. It is added as GENERATED BY DEFAULT first so the
    #    backfill UPDATE (step 2) is permitted — Postgres forbids a direct UPDATE of a
    #    GENERATED ALWAYS identity column ("can only be updated to DEFAULT"). Identity fills `seq`
    #    for ALL existing rows immediately (undeterministic physical order) — the column is
    #    effectively NOT NULL already at this point; step 2 rewrites it to the deterministic order.
    op.execute("ALTER TABLE chat_steps ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY")

    # 2. Backfill deterministic historical order: rewrite seq via ROW_NUMBER() over (created_at, id)
    #    — the exact order used before this fix (incl. id tie-break for same-transaction rows). This
    #    preserves the prior reconstruction order for historical sessions (not worse than before).
    op.execute(
        """
        WITH ordered AS (
            SELECT id, ROW_NUMBER() OVER (ORDER BY created_at, id) AS rn
            FROM chat_steps
        )
        UPDATE chat_steps cs
        SET seq = ordered.rn
        FROM ordered
        WHERE cs.id = ordered.id
        """
    )

    # 3. Advance the identity sequence above max(seq) so new inserts do not collide with the
    #    backfilled values (which were rewritten out from under the identity counter). COALESCE
    #    handles an empty table (restart at 1).
    op.execute(
        """
        SELECT setval(
            pg_get_serial_sequence('chat_steps', 'seq'),
            (SELECT COALESCE(MAX(seq), 0) + 1 FROM chat_steps),
            false
        )
        """
    )

    # 4. Lock the column to GENERATED ALWAYS (matches the ORM model: code never sets seq; the DB
    #    always assigns it on INSERT). Done AFTER backfill since ALWAYS would forbid the UPDATE.
    op.execute("ALTER TABLE chat_steps ALTER COLUMN seq SET GENERATED ALWAYS")

    # 5. Confirm NOT NULL (no-op after identity + backfill; kept for explicitness / invariant).
    op.execute("ALTER TABLE chat_steps ALTER COLUMN seq SET NOT NULL")

    # 6. Swap the reconstruction index: (session_id, created_at) -> (session_id, seq). The
    #    message-step index is left untouched.
    op.drop_index("ix_steps_session_created", table_name="chat_steps")
    op.create_index("ix_steps_session_seq", "chat_steps", ["session_id", "seq"])


def downgrade() -> None:
    # Reverse: restore the old index and drop the seq column (the identity sequence is dropped
    # automatically with the column).
    op.drop_index("ix_steps_session_seq", table_name="chat_steps")
    op.create_index("ix_steps_session_created", "chat_steps", ["session_id", "created_at"])
    op.execute("ALTER TABLE chat_steps DROP COLUMN seq")
